# -*- coding: utf-8 -*-
"""YinpengSu-40211847-Gym_3Level-INSE6220-PCA&Machine_Learning-FinalProject.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1f3NLEIVJn4UAgy3iPLlSeW_szOom_N5o

# INSE 6220 Final Project
Yinpeng Su - 40211847

Gym_3Level-INSE6220 PCA + Multi-Classification (Gym Member Dataset)

**Dataset:** Gym member motion tracking dataset

**Task:** Predict `Experience_Level` (1=Beginner, 2=Intermediate, 3=Advanced) using physiological and motion features.

**Method:** Use PCA for dimensionality reduction + PyCaret for multi-classification.

### **Principal Component Analysis**

PCA stands for Principal Component Analysis, and it is a widely used technique in data analysis and machine learning for reducing the dimensionality of large datasets. The basic idea behind PCA is to transform a set of high-dimensional variables into a smaller set of uncorrelated variables called principal components, while retaining as much of the original variance as possible.

**Import Libraries**
"""

import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
sns.set_theme(style="darkgrid")
import pandas as pd
plt.rcParams['figure.figsize'] = (7,5)

from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler

print("Pandas version: ", pd.__version__)
print("Seaborn version: ", sns.__version__)

"""**Dataset**

## Dataset

This project uses the **Gym Members Exercise Tracking** dataset (tabular data with 973 records).
Each record represents one gym member (or one tracked profile) with demographic, physiological, and workout-related features.

### Key Features
- **Age**: age of the gym member  
- **Gender**: Male / Female  
- **Weight (kg), Height (m), BMI**: body measurements  
- **Max_BPM, Avg_BPM, Resting_BPM**: heart rate metrics  
- **Session_Duration (hours), Calories_Burned**: workout session statistics  
- **Workout_Type**: Cardio / Strength / Yoga / HIIT  
- **Fat_Percentage**: body fat percentage  
- **Water_Intake (liters), Workout_Frequency (days/week)**: workout habit indicators  
- **Experience_Level**: target label (1=Beginner, 2=Intermediate, 3=Expert)
- **BMI**: Standards for measuring whether a person's weight is healthy
### Objective
We perform:
1) **PCA** to reduce dimensionality and visualize the structure of the data;  
2) **Multiclass classification** to predict `Experience_Level` from the features.


https://www.kaggle.com/datasets/valakhorasani/gym-members-exercise-dataset?utm_source=chatgpt.com

**Read the dataset**

**pd.read_csv** is a function in the pandas library in Python that is used to read a CSV (Comma Separated Values) file and convert it into a pandas DataFrame.
"""

from google.colab import drive
drive.mount('/content/drive')

import os

os.listdir('/content/drive/MyDrive/Colab Notebooks')

#read cvs file into dataframe
dfOriginal = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/gym_members_exercise_tracking.csv')
dfOriginal.head(10)

dfOriginal.info()

"""### Feature Selection for This Study

Although the original dataset contains a wide range of variables, this study focuses on a **subset of body composition and workout duration features** in order to examine their relationship with exercise experience level.

The selected features used in this analysis are:

- **Weight (kg)**: body weight of the gym member  
- **Height (m)**: height of the gym member  
- **BMI**: body mass index, representing body composition  
- **Fat_Percentage**: percentage of body fat  
- **Session_Duration (hours)**: duration of each workout session  

Other variables in the original dataset (such as Workout Frequency and water intake) were excluded from this analysis to reduce redundancy and to focus on the impact of **body-related attributes and workout duration** on exercise experience.

### Target Variable

- **Experience_Level**: workout experience level of the member  
  - 1 = Beginner  
  - 2 = Intermediate  
  - 3 = Expert  

### Objective

The objectives of this project are:

1. To apply **Principal Component Analysis (PCA)** on the selected features to reduce dimensionality and
   analyze the main sources of variation among gym members.
2. To perform **multiclass classification** to predict `Experience_Level` based on the selected features.
    
"""

#read cvs file into dataframe
df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/gym_members_exercise_tracking_selected.csv')
df.head(10)

df.info()

"""1) 973 entries

→ A total of 973 samples (973 members/records)

2) 8 columns

→ A total of 7 columns

Among them:

2 columns are object (categorical): Gender, Workout_Type

6 columns are numeric: 5 float64 + 1 int64

The target column (label) is: Experience_Level (int64)

"""

print("Number of duplicated rows is: ", df.duplicated().sum())

print("Number of rows with NaNs is: ", df.isna().any(axis=1).sum())

"""**Exploratory Data Analysis**

**sns.pairplot** is a function in the seaborn library in Python that is used to plot pairwise relationships between multiple variables in a dataset. The resulting plot is a grid of scatterplots, with each variable plotted against every other variable.
"""

plt.figure(figsize=(50, 50))
sns.pairplot(df, hue='Experience_Level')
plt.show()

y =df['Experience_Level']
y.value_counts().plot(kind='pie')
plt.ylabel('')
plt.show()

"""**Data Matrix**

Categorical variables (`Gender`, `Workout_Type`) and the target label (`Experience_Level`) are excluded from PCA.

This is not "permanently discarded," but "the PCA step is not used for now."
"""

X = df.drop(columns=['Experience_Level','Gender','Workout_Type'])

X.head(10)

"""**Note:** For visualization clarity, feature names were abbreviated eg:
    'Session_Duration (hours)' -> 'SeDur(h)',
"""

rename_dict = {
    'Weight (kg)': 'W(kg)',
    'Height (m)': 'H(m)',
    'Session_Duration (hours)': 'SeDur(h)',
    'Fat_Percentage': 'Fat(%)',
    'BMI': 'BMI'
}
X = X.rename(columns=rename_dict)

X.describe().transpose()

"""**Standardize the Data**"""

Xs = StandardScaler().fit_transform(X)
Xcols = X.columns
X = pd.DataFrame(Xs)
X.columns = Xcols
X.head(10)

"""**Observations and variables**"""

observations = list(df.index)
variables = list(X.columns)

"""**Box and Whisker Plots**"""

plt.figure(figsize=(25, 15))
ax = plt.figure()
ax = sns.boxplot(data=X, orient="v", palette="Set2")
# Rotate x-axis tick labels
ax.tick_params(axis='x', labelrotation=45)

# Use swarmplot() or stripplot to show the datapoints on top of the boxes:
#plt. figure()
plt.figure(figsize=(25, 20))
ax = plt.figure()
ax = sns.boxplot(data=X, orient="v", palette="Set2")
ax = sns.stripplot(data=X, color=".25")
ax.tick_params(axis='x', labelrotation=45)

"""**Correlation Matrix**"""

plt.figure(figsize=(15, 15))
ax = sns.heatmap(X.corr(), cmap='RdYlGn_r', linewidths=0.5, annot=True, cbar=False, square=True)
plt.yticks(rotation=0)
ax.tick_params(labelbottom=False,labeltop=True)
ax.tick_params(axis='x', labelrotation=45)
ax.tick_params(axis='y', labelrotation=45)

#X.corr().style.background_gradient(cmap='coolwarm').set_precision(2)
#sns.clustermap(X.corr(), annot=True, fmt='.2f')

"""##**Applying PCA**"""

pca = PCA()
Z = pca.fit_transform(X)

# indices for Experience_Level (assume 1/2/3)
idx_1 = np.where(y == 1)
idx_2 = np.where(y == 2)
idx_3 = np.where(y == 3)

plt.figure()
plt.scatter(Z[idx_1,0], Z[idx_1,1], label='Level 1')
plt.scatter(Z[idx_2,0], Z[idx_2,1], label='Level 2')
plt.scatter(Z[idx_3,0], Z[idx_3,1], label='Level 3')
plt.legend()
plt.xlabel('$Z_1$')
plt.ylabel('$Z_2$')
plt.title('PCA: PC1 vs PC2 (Experience Level)')
plt.show()

"""**Eigenvectors**"""

A = pca.components_.T

plt.scatter(A[:,0],A[:,1],c='r')
plt.xlabel('$A_1$')
plt.ylabel('$A_2$')
for label, x, y in zip(variables, A[:, 0], A[:, 1]):
  plt.annotate(label, xy=(x, y), xytext=(-2, 2), textcoords='offset points', ha='right', va='bottom')

plt.scatter(A[:, 0],A[:, 1], marker='o', c=A[:, 2], s=A[:, 3]*500, cmap=plt.get_cmap('Spectral'))
plt.xlabel('$A_1$')
plt.ylabel('$A_2$')
for label, x, y in zip(variables,A[:, 0],A[:, 1]):
  plt.annotate(label,xy=(x, y), xytext=(-20, 20),
      textcoords='offset points', ha='right', va='bottom',
      bbox=dict(boxstyle='round,pad=0.5', fc='yellow', alpha=0.5),
      arrowprops=dict(arrowstyle = '->', connectionstyle='arc3,rad=0'))

"""**Scree plot**"""

#Eigenvalues
Lambda = pca.explained_variance_

#Scree plot
x = np.arange(len(Lambda)) + 1
plt.plot(x,Lambda/sum(Lambda), 'ro-', lw=3)
plt.xticks(x, [""+str(i) for i in x], rotation=0)
plt.xlabel('Number of components')
plt.ylabel('Explained variance')

"""**Explained Variance**"""

ell = pca.explained_variance_ratio_
ind = np.arange(len(ell))
plt.bar(ind, ell, align='center', alpha=0.5)
plt.plot(np.cumsum(ell))
plt.xlabel('Number of components')
plt.ylabel('Cumulative explained variance')

"""**Biplot**"""

# 0,1 denote PC1 and PC2
A1 = A[:, 0]
A2 = A[:, 1]
Z1 = Z[:, 0]
Z2 = Z[:, 1]

plt.figure(figsize=(20, 15))
plt.xlabel('$Z_1$ (PC1)')
plt.ylabel('$Z_2$ (PC2)')

# arrows project features as vectors onto PC axes
for i in range(len(A1)):
    plt.arrow(
        0, 0,
        A1[i] * max(Z1), A2[i] * max(Z2),
        color='k', width=0.0005, head_width=0.02
    )
    plt.text(
        A1[i] * max(Z1) * 1.15,
        A2[i] * max(Z2) * 1.15,
        variables[i],
        color='k'
    )

# --- replace wheat classes with Experience_Level classes ---
idx_1 = np.where(y == 1)
idx_2 = np.where(y == 2)
idx_3 = np.where(y == 3)

plt.scatter(Z[idx_1, 0], Z[idx_1, 1], label='Level 1', alpha=0.7)
plt.scatter(Z[idx_2, 0], Z[idx_2, 1], label='Level 2', alpha=0.7)
plt.scatter(Z[idx_3, 0], Z[idx_3, 1], label='Level 3', alpha=0.7)

plt.legend(loc='upper left')
plt.title('Biplot (PC1 vs PC2)')
plt.show()

"""##**Using PCA Library**"""

!pip install pca

from pca import pca
# Initialize and keep all PCs
model = pca(n_components=0.85)
# Fit transform
out = model.fit_transform(X)

"""**Principal Components**"""

out['PC']

"""**Scatter plot**"""

model.scatter(label=True, legend=False)

"""**Eigenvectors**"""

A = out['loadings'].T

sns.scatterplot(data=A, x="PC1", y="PC2")
plt.xlabel('$A_1$')
plt.ylabel('$A_2$')
for i in range(A.shape[0]):
 plt.text(x=A.PC1[i]+0.02,y=A.PC2[i]+0.02, s=variables[i],
          fontdict=dict(color='red',size=10),
          bbox=dict(facecolor='yellow',alpha=0.5))

"""**Scree Plot**"""

VR = out['variance_ratio']
x = np.arange(len(VR)) + 1
plt.plot(x, VR, 'ro-', lw=3)
plt.xticks(x, [""+str(i) for i in x], rotation=0)
plt.xlabel('Number of components')
plt.ylabel('Explained variance')
plt.show()

"""**Explained Variance Plot**"""

model.plot();

"""**Biplot**

A biplot is a graphical representation of multivariate data that displays both observations and variables simultaneously in a single plot. Each observation is represented as a point in a two-dimensional plot, while the variables are represented as arrows or vectors that point in the direction of the greatest variation in the data. The length of the vector indicates the magnitude of the variable, while the angle between two vectors reflects their correlation.
"""

model.biplot(label=False, legend=False)

"""#**Multiclass Classification with PyCaret**

Multiclass classification is a supervised machine learning technique where the goal is to classify instances into one of three or more classes.

**Data Splitting**


In order to demonstrate the predict_model() function on unseen data, a sample of 97(973 - 973*0.9 = 97) observations has been withheld from the original dataset to be used for predictions. This should not be confused with a train/test split as this particular split is performed to simulate a real life scenario. Another way to think about this is that these 97 records were not available at the time when the machine learning experiment was performed.
"""

data = df.sample(frac=0.9, random_state=786)
data_unseen = df.drop(data.index)

data.reset_index(drop=True, inplace=True)
data_unseen.reset_index(drop=True, inplace=True)

print('Data for Modeling: ' + str(data.shape))
print('Unseen Data For Predictions: ' + str(data_unseen.shape))

"""## **Install PyCaret**

PyCaret is an open-source, low-code machine learning library in Python designed to make the end-to-end machine learning process easier and faster for both beginners and experienced data scientists. It offers a variety of tools and functions for data preparation, model training, model selection, and deployment.

pip3 install pycaret==2.3.6 is a command used to install a specific version of the PyCaret library in Python. If you encounter an error message, try running the code again.
"""

# install slim version (default)
!pip install pycaret

"""**Setting up the Environment in PyCaret**

The **setup()** function initializes the environment in pycaret and creates the transformation pipeline to prepare the data for modeling and deployment. setup() must be called before executing any other function in pycaret. It takes two mandatory parameters: a pandas dataframe and the name of the target column. All other parameters are optional and are used to customize the pre-processing pipeline.

When setup() is executed, PyCaret's inference algorithm will automatically infer the data types for all features based on certain properties. The data type should be inferred correctly but this is not always the case. To account for this, PyCaret displays a table containing the features and their inferred data types after setup() is executed. If all of the data types are correctly identified enter can be pressed to continue or quit can be typed to end the expriment. Ensuring that the data types are correct is of fundamental importance in PyCaret as it automatically performs a few pre-processing tasks which are imperative to any machine learning experiment. These tasks are performed differently for each data type which means it is very important for them to be correctly configured.
"""

from pycaret.classification import *
clf = setup(data=data, target='Experience_Level', train_size=0.7, session_id=123)

"""Once the `setup()` function is successfully executed, PyCaret displays an information grid summarizing the modeling configuration and preprocessing pipeline. The key observations from this setup are as follows:

- **Session ID**:  
  A fixed session ID (123) is used to ensure reproducibility of all modeling results.

- **Target Variable**:  
  The target variable is **Experience_Level**, representing exercise experience with three classes  
  (1 = Beginner, 2 = Intermediate, 3 = Expert).

- **Target Type**:  
  The problem is correctly identified as a **multiclass classification** task.

- **Target Mapping**:  
  PyCaret internally encodes the target labels as:
  - 1 → 0  
  - 2 → 1  
  - 3 → 2  
  This encoding is used internally for model training and does not affect interpretability.

- **Original Data Shape**:  
  The modeling dataset contains **876 samples and 8 columns**, including the target variable.

- **Feature Types**:  
  - **Numeric features**: 5  
    (Weight, Height, Session Duration, Fat Percentage, BMI)  
  - **Categorical features**: 2  
    These categorical variables are automatically handled using one-hot encoding.

- **Preprocessing Pipeline**:  
  PyCaret automatically performs essential preprocessing steps, including:
  - Missing value imputation (mean for numeric, mode for categorical features)
  - Encoding of categorical variables
  - Train–test splitting

- **Transformed Data Shape**:  
  After preprocessing and encoding, the dataset is transformed into **11 features**.

- **Train/Test Split**:  
  The data is split into:
  - **Training set**: 613 samples (70%)  
  - **Test set**: 263 samples (30%)

Overall, this setup confirms that the dataset has been correctly prepared for multiclass classification, with appropriate preprocessing applied automatically by PyCaret.

**Comparing all Machine Learning Models**
"""

#show the best model and their statistics
 best_model = compare_models()

best_model

"""## Comparing Models (PyCaret)

We used `compare_models()` to benchmark multiple classification algorithms using **stratified 10-fold cross-validation**.  
The evaluation metrics reported include Accuracy, Recall, Precision, F1, Kappa, and MCC.

### Result
No1.Random Forest (rf)：Accuracy ≈ 0.7583，F1 ≈ 0.7497

No2.XGBoost (xgboost)：Accuracy ≈ 0.7519，F1 ≈ 0.7489

No3.Naive Bayes (nb)：Accuracy ≈ 0.7503，F1 ≈ 0.7428


Based on the cross-validated results, **Random Forest (rf)** achieved the best overall performance on this dataset.
Therefore, Random Forest was selected as the **baseline best model** for further tuning and evaluation.

Note: Other 2 models **Extreme Gradient Boosting** and **Naive Bayes** achieved very similar

###Create a Model

create_model is the most granular function in PyCaret and is often the foundation behind most of the PyCaret functionalities. As the name suggests this function trains and evaluates a model using cross validation that can be set with fold parameter. The output prints a score grid that shows Accuracy, Recall, Precision, F1, Kappa and MCC by fold.

**Create Random Forest Classifier**
"""

from pycaret.classification import *

clf = setup(
    data=data,
    target='Experience_Level',
    train_size=0.7,
    session_id=123
)
rf = create_model('rf')

#trained model object is stored in the variable 'rf'.
rf

"""## Random Forest (rf) Baseline Model

We trained a **Random Forest classifier** using PyCaret’s `create_model('rf')`, evaluated with **stratified 10-fold cross-validation**.

### Cross-Validation Performance (10 folds)

The model achieved the following average performance across folds:

- **Mean Accuracy = 0.7583**
- **Mean F1 = 0.7497**
- **Mean Precision = 0.7675**
- **Mean Recall = 0.7583**
- **Mean MCC = 0.6273**
- **Mean Kappa = 0.6132**

### Stability Across Folds

The variation across folds was moderate:

- **Std (Accuracy) = 0.0472**
- **Std (F1) = 0.0523**

This indicates that the Random Forest model provides **relatively stable generalization** across different train/validation splits. Compared with a single decision tree, Random Forest typically reduces overfitting by averaging many trees trained on bootstrapped samples and randomized feature subsets.

### Tune a Model:
How to automatically tune the hyper-parameters of a multiclass model. When a model is created using the create_model() function it uses the default hyperparameters. In order to tune hyperparameters, the tune_model() function is used. The tune_model() function is a random grid search of hyperparameters over a pre-defined search space. By default, it is set to optimize Accuracy but this can be changed using optimize parameter. This function automatically tunes the hyperparameters of a model on a pre-defined search space and scores it using stratified cross validation. The output prints a score grid that shows Accuracy, AUC, Recall, Precision, F1 and Kappa by fold.

**Tune Random Forest Model**
"""

tuned_rf = tune_model(rf)

#tuned model object is stored in the variable 'tuned_rf'.
tuned_rf

"""## Hyperparameter Tuning (Random Forest)

After establishing Random Forest as the best-performing baseline model, we further improved its performance using PyCaret’s `tune_model()` function.

The tuning process performs a randomized grid search over a predefined hyperparameter space and evaluates candidate configurations using **stratified 10-fold cross-validation**. By default, the optimization objective is **Accuracy**.

### Tuned Model Performance

After hyperparameter tuning, the Random Forest classifier achieved the following average performance:

- **Mean Accuracy = 0.7959**
- **Mean F1 = 0.7752**
- **Mean Precision = 0.8616**
- **Mean Recall = 0.7959**
- **Mean MCC = 0.7224**
- **Mean Kappa = 0.6707**

The performance variance across folds remained moderate:

- **Std (Accuracy) = 0.0481**
- **Std (F1) = 0.0609**

### Comparison with Baseline Model

Compared to the baseline Random Forest model, hyperparameter tuning led to a noticeable improvement:

- Accuracy increased from **0.7583 to 0.7959**
- F1-score increased from **0.7497 to 0.7752**

This improvement indicates that tuning enhanced the model’s ability to generalize across different training splits.

### Tuned Hyperparameters

The tuned Random Forest model uses a more regularized configuration, including:

- Reduced tree depth (`max_depth = 3`)
- Increased minimum samples per split and leaf  
  (`min_samples_split = 9`, `min_samples_leaf = 4`)
- Fewer trees (`n_estimators = 70`)
- Disabled bootstrap sampling

These constraints reduce overfitting while preserving sufficient model complexity, leading to better generalization performance.

Overall, hyperparameter tuning significantly improved the Random Forest classifier’s predictive performance and stability.

**Evaluate Random Forest Model**

Here is how to analyze model performance using various plots
"""

evaluate_model(tuned_rf)

"""**Create Extreme Gradient Boosting Model**"""

xgboost = create_model('xgboost')

"""**Tune Extreme Gradient Boosting Model**"""

tuned_xgboost = tune_model(xgboost)

tuned_xgboost

"""**Evaluate Extreme Gradient Boosting Model**"""

evaluate_model(tuned_xgboost)

"""**Create Naive Bayes Model**"""

nb = create_model('nb')

nb

"""**Tune Naive Bayes Model**"""

tuned_nb = tune_model(nb)

tuned_nb

"""**Evaluate Naive Bayes Model**"""

evaluate_model(tuned_nb)

"""**Create Extra Trees Classifier Model**"""

et = create_model('et')

"""**Tune Extra Trees Classifier Model**"""

tuned_et = tune_model(et)

"""**Evaluate Extra Trees Classifier Model**"""

evaluate_model(tuned_et)

"""#**Tune the Best Model**"""

# Tune hyperparameters with scikit-learn (default)
tuned_best_model = tune_model(best_model)

tuned_best_model

"""**Evaluate the Best Model**

One way to analyze the performance of models is to use the evaluate_model() function which displays a user interface for all of the available plots for a given model. It internally uses the plot_model() function.
"""

evaluate_model(tuned_best_model)

"""#**Classification + PCA**"""

clf_pca = setup(data=df, target='Experience_Level', train_size=0.7, session_id=123, normalize = True, pca = True, pca_components = 3)

#show the best model and their statistics
best_model_pca = compare_models()

best_model_pca

"""**Tune the Best Model**"""

# Tune hyperparameters with scikit-learn (default)
tuned_best_model_pca = tune_model(best_model_pca)

tuned_best_model_pca

"""**Evaluate the Best Model**

One way to analyze the performance of models is to use the evaluate_model() function which displays a user interface for all of the available plots for a given model. It internally uses the plot_model() function.
"""

evaluate_model(tuned_best_model_pca)

"""**Note:** The AUC metric is not available for Multiclass classification however the column will still be shown with zero values to maintain consistency between the Binary Classification and Multiclass Classification display grids."""

lda_pca = create_model('lda')

tuned_lda_pca = tune_model(lda_pca)

"""#**Explainable AI with Shapley values**

Shapley values are a widely used approach from cooperative game theory that come with desirable properties.

Since the following can only be performed within tree-type machine learning, we use the second-best random forest.
"""

rf_pca = create_model('rf')

tuned_rf_pca = tune_model(rf_pca)

"""## **Install Analysis Extras for Explainable AI**"""

!pip install pycaret[analysis]

"""**SHAP Summary Plot**

Rather than using a typical feature importance bar chart, we use a density scatter plot of SHAP values for each feature to identify how much impact each feature has on the model output for individuals in the validation dataset. Features are sorted by the sum of the SHAP value magnitudes across all samples.
"""

interpret_model(tuned_rf_pca, plot='summary')

#explainer = shap.TreeExplainer(tuned_lda_pca)
#X = df.drop('Experience_Level', axis=1)
#shap_values = explainer.shap_values(X)
#shap.summary_plot(shap_values, X)

"""**Visualize a single prediction**"""

interpret_model(tuned_rf_pca, plot='reason', observation=32)

"""From the above the plot, we can see the "base value," which is defined as the mean predicted target; and f(x), which is the prediction for a selected observation (i.e. observation number 32). The red-colored features increased the predicted value, while the blue-colored features decreased it. The size of each feature (i.e. Principal Component) indicates the impact it has on the model.

**Visualize many predictions**
"""

interpret_model(tuned_rf_pca, plot='reason')
